// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Configuration() {
  return window['go']['main']['App']['Configuration']();
}

export function Copy(arg1) {
  return window['go']['main']['App']['Copy'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function SaveDestination(arg1) {
  return window['go']['main']['App']['SaveDestination'](arg1);
}

export function SaveSource(arg1) {
  return window['go']['main']['App']['SaveSource'](arg1);
}
