// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BookInfo(arg1:string):Promise<main.Book>;

export function Configuration():Promise<main.Config>;

export function Copy(arg1:main.CD):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Info():Promise<main.CD>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function SaveDestination(arg1:string):Promise<void>;

export function SaveSource(arg1:string):Promise<void>;
