name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
    
      - name: Setup wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest  
      
      - name: Build app
        working-directory: "./cmd/adjutant"
        run: wails build -platform windows/amd64
