name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
      
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      
      - name: Setup wails
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
      
      - name: Wails build
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: "test"
          build-platform: "windows/amd64"
          go-version: 1.21
          package: false
          nsis: false

