name: release

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-windows
        path: adjutant.exe

  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-ubuntu
        path: adjutant

  release:
    name: release
    needs: [build-windows, build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: download widows app
        uses: actions/download-artifact@v3
        with:
          name: adjutant-windows
      - name: download linux app
        uses: actions/download-artifact@v3
        with:
          name: adjutant-ubuntu
      - run: ls *
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files:
            */adjutant*