name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=${{matrix.os}} GOARCH=amd64 go build -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-${{matrix.os}}
        path: adjutant*
        retention-days: 5

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list assets
        run: ls -R
      
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files:
            ./**