name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, 386]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o adjutant-${{matrix.os}}-${{matrix.arch}} -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-${{matrix.os}}-${{matrix.arch}}
        path: adjutant-${{matrix.os}}-${{matrix.arch}}*

  build-windows:
    name: build-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build -v ./...
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-windows
        path: adjutant.exe

  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-ubuntu
        path: adjutant

  release:
    name: release
    needs: [build-windows, build-ubuntu, build]
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files:
            ./adjutant*