name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.x
    
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true
        
    - name: Setup wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Set version
      working-directory: "./cmd/adjutant"
      run: |
        version=$(echo "${{github.ref_name}}" | cut -d 'v' -f 2)
        jq --arg v "$version.0" '(.info.productVersion) |= $v' .\wails.json >> .\wails.json

    - name: Build app
      working-directory: "./cmd/adjutant"
      run: wails build -platform ${{matrix.os}}/amd64 -upx

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adjutant-${{matrix.os}}
        path: cmd/adjutant/build/bin/adjutant*
        retention-days: 5

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list assets
        run: ls -R
      
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          draft: false
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files:
            ./**